env:
  env_name: push-v2
  num_trajs: 1000
  num_test_trajs: 50  
  horizon: 100
  #quad1
  train_range_goal_low: [0., 0.5, 0.01] #z: [0.275, 0.275]
  train_range_goal_high: [0.3, 0.7, 0.01] 
  #quad2
  test_range_goal_low: [-0.3, 0.5, 0.01] #y,z: [0.4, 0.7], [0.275, 0.275]
  test_range_goal_high: [0., 0.7, 0.01]
  #obs/plot/goal idxs post processing
  obs_idxs: [0, 1, 2, 3, 4, 5, 6]
  # plot_idxs: [0, 1, 2] # gripper
  # plot_idxs: [0, 1] # gripper 2D
  plot_idxs: [4, 5 ,6] # obj
  # plot_idxs: [4, 5] # obj 2D (plotting z axis can show poor performance but margin can actually be small)
  goal_idxs: [-3, -2, -1]  
  post_process: true
  post_process_idxs: [0, 1, 2, 3, 4, 5, 6, 36, 37, 38]
  seed: 0

model:  
  hidden_layer_size: 32
  hidden_depth: 1
  feature_dim: 32
  batch_size: 32
  num_epochs: 5000
  transducer_mode: delta