env:
  env_name: reach-v2
  num_trajs: 1000
  num_test_trajs: 50  
  horizon: 100
  #quad1
  train_range_goal_low: [0., 0.7, 0.05] #z: [0.275, 0.275]
  train_range_goal_high: [0.4, 0.9, 0.3] 
  #quad2
  test_range_goal_low: [-0.4, 0.7, 0.05] #y,z: [0.4, 0.7], [0.275, 0.275]
  test_range_goal_high: [0., 0.9, 0.3]
  #
  obs_idxs: [0, 1, 2]
  plot_idxs: [0, 1, 2]
  goal_idxs: [-3, -2, -1]  
  post_process: true
  post_process_idxs: [0, 1, 2, 36, 37, 38]
  seed: 0

model:  
  hidden_layer_size: 32
  hidden_depth: 1
  feature_dim: 32
  batch_size: 32
  num_epochs: 5000
  transducer_mode: delta
 